=== Damiano-Bianda/DBMS/schemi_xml/GolfCompetition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="golfCompetition">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:string"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="date" type="xs:date"/>
        <xs:element name="sponsor" type="xs:string"/>
        <xs:element name="buche">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="buca" minOccurs="9" maxOccurs="9">
                <xs:complexType>
                  <xs:attribute name="par" type="parT" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="category" maxOccurs="7">
          <xs:complexType>
            <xs:attribute name="from" type="HandicapT"/>
            <xs:attribute name="to" type="HandicapT"/>
            <xs:attribute name="type" type="CategoryType" use="required"/>
            <xs:attribute name="numPrize" type="NumPrizeT" use="required"/>
            <xs:attribute name="age" type="xs:integer"/>
          </xs:complexType>
        </xs:element>
        <xs:element name="reserved" type="xs:boolean" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="HandicapT">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="36"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="CategoryType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="First"/>
      <xs:enumeration value="Second"/>
      <xs:enumeration value="Third"/>
      <xs:enumeration value="Forth"/>
      <xs:enumeration value="Fifth"/>
      <xs:enumeration value="Lady"/>
      <xs:enumeration value="Over"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="NumPrizeT">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="parT">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1"/>
      <xs:maxInclusive value="10"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Damiano-Bianda/DBMS/schemi_xml/esempio_gara.xml
<?xml version="1.0" encoding="UTF-8"?>
<golfCompetition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GolfCompetition.xsd">
  <name>Coppa del presidente</name>
  <date>2009-12-25</date>
  <sponsor>Lavazza S.p.A</sponsor>
  <buche>
    <buca par="4"/>
    <buca par="5"/>
    <buca par="3"/>
    <buca par="4"/>
    <buca par="4"/>
    <buca par="5"/>
    <buca par="3"/>
    <buca par="5"/>
    <buca par="3"/>
  </buche>
  <category numPrize="3" from="0" to="15" type="First"/>
  <category numPrize="3" from="16" to="36" type="Second"/>
  <category numPrize="1" type="Lady"/>
  <category numPrize="1" type="Over" age="40"/>
</golfCompetition>
